# 서버 포트 설정
server:
  port: 8088

# 업로드 경로 설정 (Spring 바깥에 위치)
file:
  upload-dir: ./uploads/images/

spring:
  application:
    name: SHOP

  output:
    ansi:
      enabled: always

  # 데이터베이스 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/shopdatabases?useSSL=false&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: shop
    password: 1234
